advertisement/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name='advertisement'

urlpatterns = [
    path('ads/', views.AdvList.as_view(), name='adv_list'),
    path('M-ads/', views.AdvListForModerator.as_view(), name='adv_list_for_moderators'),

    path('add/adv/', views.AdvAdd.as_view(), name='add_adv'),
    path('editing/<str:url_identifier>/', views.AdvUpdate.as_view(), name='update_adv'),

    path('adv/<str:url_identifier>/', views.AdvDetail.as_view(), name='adv_detail'),

    path('object/<str:type_>/', views.adv_by_type, name='adv_by_obj_type'),

    path('adv/<int:id>/archiving/', views.add_adv_to_archive, name='add_adv_to_archive'),

    path('archive/', views.Archive.as_view(), name='archive'),

    path('get-phone-ajax', views.get_adv_phone_ajax, name='get_adv_phone_ajax'),

    path('load-values-ajax/', views.load_values_ajax, name='load_values_ajax')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

# app_name = 'config'

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('', include('advertisement.urls')),
    path('', include('user.urls')),
    path('', include('filters.urls')),
    path('', include('auth_user.urls')),
    path('', include('site_messages.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.base_redirector, name='base_redirector_url'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('profile/', views.Profile.as_view(), name='profile'),
    path('likedAds/', views.UserLikedAds.as_view(), name='user_ads'),
    path('add-adv-ajax/', views.add_adv_ajax, name='add_adv_ajax'),
    path('hide-adv/<int:adv_id>', views.hide_adv, name='hide_adv'),
    path('hidden-ads/', views.HiddenAds.as_view(), name='hidden_ads'),
    path('viewed-ads/', views.ViewedAds.as_view(), name='viewed_ads'),
]

advertisement/forms.py
from django import forms

from .models import Advertisement, City, Region, District, Street
from filters.forms import NameSetterModelForm


class AdvUpdateForm(NameSetterModelForm):

    class Meta:
        model = Advertisement
        exclude = ('date_pub', 'title_slug', 'photo_links',
                   'seller_id', 'original_url')

class AdvAddForm(NameSetterModelForm):

    images = forms.ImageField(
        label='Зоображення',
        widget=forms.ClearableFileInput(attrs={'multiple':True})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['region'].initial = Region.objects.get(name='Львівська')
        self.fields['region'].queryset = Region.objects.all()
        # self.fields['city'].queryset = City.objects.none()
        # self.fields['district'].queryset = District.objects.none()
        # self.fields['street'].queryset = Street.objects.none()

    class Meta:
        model = Advertisement
        exclude = ('date_pub', 'title_slug', 'photo_links',
                   'seller_id', 'original_url')

advertisement/views.py
import logging

from django.views import generic
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views.generic.edit import FormView

from advertisement.models import Advertisement, Street, District, Region, City
from .forms import AdvUpdateForm, AdvAddForm
from . import services, decorators

from user import services as user_services
from site_messages.forms import MessageForm
from site_messages.services import MessageManager

logger = logging.getLogger(__name__)


class AdvList(services.AdvListMixin):
    template_name = 'advertisement/AdvList.html'

    def get(self, request):
        return super(AdvList, self).get(request)


class AdvListForModerator(services.AdvListMixin):
    template_name = 'advertisement/AdvListForModerator.html'


class AdvDetail(generic.DetailView):
    model = Advertisement

    slug_field = 'url_identifier'
    slug_url_kwarg = 'url_identifier'

    template_name = None  # I am using "template_setter" decorator for detecting template. Read why in doc
    context_object_name = 'advertisement'

    @decorators.template_setter
    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        user_services.UserAdv(adv=self.object, user=request.user).add_reviewed_adv_for_user()
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['random_adv'] = services.get_random_adv(current_adv_id=self.object.id)
        context['message_form'] = MessageForm()
        message_manager = MessageManager(self.request.GET.get('client_id'), self.object, self.request.user)
        context['messages'] = message_manager.get_messages()
        context['adv_clients'] = message_manager.clients_id if hasattr(message_manager, 'clients_id') else None
        return context

    @decorators.template_setter
    def post(self, request, url_identifier, *args, **kwargs):
        form = MessageForm(request.POST)

        if form.is_valid():
            manager = MessageManager(
                client_id=request.GET.get('client_id'),
                adv=Advertisement.objects.get( url_identifier= url_identifier), user=request.user
            )
            manager.send_messages(form.cleaned_data['text'])
            return HttpResponseRedirect(f'{request.get_full_path()}#messages-block')
        return render(request, self.template_name)


def adv_by_type(request, type_):
    ads_page_list = services.AdsPaginator(request.GET.get('page', 1), search_criteria=type_)
    context = ads_page_list.get_context()
    return render(request, 'advertisement/AdvList.html', context=context)


class AdvAdd(LoginRequiredMixin, CreateView):
    login_url = '/accounts/login/'

    template_name = 'advertisement/AdvertisementCreating.html'

    model = Advertisement
    form_class = AdvAddForm

    def post(self, request, *args, **kwargs):
        form = self.get_form(self.get_form_class())
        if form.is_valid():
            result = self.form_valid(form)
            services.store_adv_images(adv=self.object, images=request.FILES.getlist('images'))
            return result
        return render(request, self.template_name, {'form': form})


class AdvUpdate(PermissionRequiredMixin, UpdateView):

    permission_required = 'advertisement.change_advertisement'

    slug_field = 'url_identifier'
    slug_url_kwarg = 'url_identifier'

    template_name = 'advertisement/AdvUpdate.html'
    model = Advertisement
    form_class = AdvUpdateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['adv'] = self.object
        return context


def add_adv_to_archive(request, id):
    archiver = services.Archiver(id)
    return HttpResponseRedirect(archiver.get_end_point_for_redirect(request.GET.get('redirect_to')))


class Archive(services.AdvListMixin):
    template_name = 'advertisement/archive.html'
    order_by = '-date_archival'

    search_archival = True


def get_adv_phone_ajax(request):
    adv_id = request.POST.get('adv_id')

    phone = Advertisement.get_phone(adv_id)
    return JsonResponse({'adv_id': adv_id, 'button_id': request.POST.get('button_id'),
                         'is_authenticated': request.user.is_authenticated, 'phone': phone})


def load_values_ajax(request):
    field_changed = request.GET.get('field_changed')[1:]
    value_id = request.GET.get('value_id')

    if not value_id:
        return render(request, 'includes/dropdown_list_options.html')

    reg_id = request.GET.get('current_region')
    cit_id = request.GET.get('current_city')
    dist_id = request.GET.get('current_district')
    str_id = request.GET.get('current_street')

    current_region = Region.objects.get(id=reg_id) if reg_id else ''
    current_city = City.objects.get(id=cit_id) if cit_id else ''
    current_district = District.objects.get(id=dist_id) if dist_id else ''
    current_street = Street.objects.get(id=str_id) if str_id else ''

    if field_changed == 'id_region':
        regions = Region.objects.exclude(id=value_id)
        cities = City.objects.filter(region_id=value_id)
        districts = District.objects.filter(region_id=value_id, is_city_district=False)

    elif field_changed == 'id_city':
        streets = Street.objects.filter(city_id=value_id)
        districts = District.objects.filter(city_id=value_id)
        cities = City.objects.exclude(id=value_id)

        if len(districts) == 1:
            current_district = districts[0]
            districts = District.objects.filter(region_id=reg_id, is_city_district=False)
        else:
            current_district = None


    elif field_changed == 'id_district':
        current_city = current_district.city
        cities = City.objects.exclude(id=current_city.id)

        if current_district.is_city_district:
            districts = District.objects.filter(city=current_district.city, is_city_district=True)
        else:
            districts = District.objects.exclude(id=value_id, is_city_district=True)


    return render(request, 'includes/dropdown_list_options.html', locals())

templates/advertisement/Adv.html
{% extends 'base.html' %}
{% load static %}

{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/get-phone-buttons.js' %}"></script>
{% endblock %}


{% block title %}
    {% if inner_include == 'update' %}
        Редагування: {{ advertisement.get_title }}
    {% else %}
        {{ advertisement.get_title }}
    {% endif %}

{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/adv-detail.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slider2.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/adv-messages.css' %}">
    {% if inner_include == 'update' %}
        <link rel="stylesheet" href="{% static 'css/adv-update.css' %}">
    {% endif %}

{% endblock %}


{% block content %}

<div class="content">

    {% include 'includes/form-error.html' %}

    <div class="container-images">
        {% include 'advertisement/includes/slider2.html' %}
    </div>
    <div class="container-info-main">
        {% if inner_include == 'update' %}
            {% include 'advertisement/includes/from-update-container-info.html' %}
        {% else %}
            {% include 'advertisement/includes/container-info.html' %}
        {% endif %}
    </div>
</div>

{% block messages %}
{% endblock %}

<div class="random-list">
    {% for adv in random_adv %}
    <div class="card">
        <a href="{{ adv.get_absolute_url }}">
            <img src="{{adv.get_main_image}}" class="card-img-top" alt="{{ adv.title }}">
        </a>

      <div class="card-body" style="height:50%">
          <a class="adv-title" href="{{ adv.get_absolute_url }}">{{ adv.get_small_title }}</a>

          {% if adv.len_gen_title < 25 %}
              <p style="height: 12px;"></p>
          {% endif %}

          <pre class="adv-price">{{ adv.price }} {{ adv.currency }}</pre>
          <pre class="adv-date">Дата публікації: {{ adv.date_pub }}</pre>
      </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/advertisement/AdvForClient.html
{% extends 'advertisement/Adv.html' %}

{% block messages %}
    {% include 'messages/messages_client.html' %}
{% endblock %}

templates/advertisement/AdvForModerator.html
{% extends 'advertisement/Adv.html' %}

{% block messages %}
    {% include 'messages/messages_moderator.html' %}
{% endblock %}

templates/advertisement/AdvList.html
{% extends 'advertisement/AdvListMainTemplate.html' %}

<title>{% block title %}Львівська нерухомість{% endblock %}</title>

{% block filters %}
    {% include 'filters/filters.html'%}
{% endblock %}

{% block adv_buttons %}
    {% if not user_adv %}
        <button type="button" class="btn btn-success add-button single" value="{{adv.id}}" id="add-{{forloop.counter}}">в корзину + </button>
    {% endif %}
    <a href="{{ adv.get_absolute_url }}" type="button" class="btn btn-light check-button single">Переглянути</a>
    <a href="{{ adv.get_absolute_url }}#messages-block" type="button" class="btn btn-light check-button single">Написати</a>


    {% if user.is_authenticated %}
    <a href="{% url 'user:hide_adv' adv.id %}?end_point={{ request.get_full_path }}" class="btn btn-light hide-button single">Не показувати</a>
    {% endif %}
{% endblock %}

templates/advertisement/AdvListForModerator.html
{% extends 'advertisement/AdvListMainTemplate.html' %}

<title>{% block title %}М - Львівська нерухомість  {% endblock %}</title>

{% block filters %}
    {% include 'filters/filters.html'%}
{% endblock %}

{% block adv_buttons %}
    {% if user.is_moderator %}
    <a type="button"  href="{% url 'advertisement:update_adv' adv.url_identifier %}" class="btn btn-warning update-button single">Редагувати</a>
    <a type="button" href="{% url 'advertisement:add_adv_to_archive' adv.id %}?redirect_to={{ request.get_full_path }}" class="btn btn-danger archive-button single" >Архівувати</a>
    {% endif %}
{% endblock %}

templates/advertisement/AdvListMainTemplate.html
{% extends 'base.html' %}
{% load static %}

{% block js %}<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>{% endblock %}
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/main-for-customer.css' %}">{% endblock %}

{% block content %}

{% block types %}
    {% include 'advertisement/includes/AdvertisementByObjectType.html'%}
{% endblock %}

{% block filters %}
{% endblock %}

{% if ads_list %}
<div class="main-advertisement-list">
    {% for adv in ads_list %}
    <div class="list-item" id="adv-{{adv.id}}">
        <section class="item-img" style="max-width: 100%">
            <a href="{{ adv.get_absolute_url }}">
                <img src="{{ adv.get_main_image}}" alt="...">
            </a>
        </section>
        <section class="section-item-info">
            <div class="info-table">
                <a href="{{ adv.get_absolute_url }}" >{{adv.get_title}}</a>
                <br>
                <pre>ID оголошення: {{ adv.id }}</pre>
                <table style="margin-top:20px;">
                    <tr>
                        <td class="adv-desc">{{adv.get_small_description}}</td>
                    </tr>
                    <tr>
                        <td>
                            <pre class="adv-addr" style="">м. {{ adv.city }}   {% if adv.street %} вул. {{ adv.street }} {% endif %}</pre>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <pre class="adv-price">Ціна:   {{ adv.price }} {{ adv.currency }}</pre>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <pre class="adv-date">Дата публікації: {{ adv.date_pub }}</pre>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <pre class="adv-price"><strong>Оригінальне посилання:</strong>   <a href="{{ adv.original_url }}">{{ adv.original_url }}</a></pre>
                        </td>
                    </tr>
                </table>
            </div>
        </section>
            <section class="item-buttons">
                {% block adv_buttons %}
                {% endblock %}
            </section>
    </div>
    <br>
    {% endfor %}


    {% if is_paginated %}
        {% include 'includes/paginator.html' %}
    {% endif %}
</div>
{% else %}

<style>
.img-not-found{
    border-radius: 20px;
}


.not-found-container {
    width: 100%;
    text-align: center;
}
</style>

<div class="not-found-container">
    <p>Не знайдено жодних оголошень</p>
    <img class="img-not-found" height="400px" alt="" src="{% static 'images/not-found.jpg' %}">
</div>
{% endif %}

{% csrf_token %}

<script >

    userIsAuthenticated = "{{ user.is_authenticated }}"

    function hideButton(buttonId){
        button = document.getElementById(buttonId)
        button.hidden = true;
    }

    function hideAdvBlock(id){
        element = document.getElementById(`adv-${id}`)
        element.style.display = 'none';

    }

    function setHiddenValueForButtons(arrButtonsId){
        buttons = document.getElementsByClassName('add-button')
        for (button of buttons){
            if (arrButtonsId.includes(button.value)){
                button.hidden = true;
            }
        }
        return buttons[0]
    }


    class AjaxAddButton{
        constructor(options) {
            this.csrf = options.csrf
            this.element = options.element
            this.url = options.url
            this.method = options.method
        }

        successFunction = function (response) {
            hideButton(response.button_id)
        }

        sendData() {
            return {
                csrfmiddlewaretoken: this.csrf,
                adv_id: this.element.val(),
                button_id: this.element.attr('id'),
            }
        }

        ajaxFunction() {
            $.ajax({
                url: this.url,
                type: this.method,
                data: this.sendData(),
                success: this.successFunction
            })
        }

    }

    $(document).ready(function () {
        var csrf = $("input[name=csrfmiddlewaretoken]").val()

        add_url = "{% url 'user:add_adv_ajax' %}"

        $(".add-button").click(function () {
            if (userIsAuthenticated === "True") {
                ajax = new AjaxAddButton({csrf: csrf, element: $(this), url: add_url, method: 'post'})
                ajax.ajaxFunction()
            } else{
                window.location.href = window.origin + `/accounts/login/?next=${window.location.href}`
            }

        })
    })

    arrButtonsId = '{{ advertisement_id }}'
    setHiddenValueForButtons(arrButtonsId)
</script>

{% endblock %}

templates/advertisement/AdvUpdate.html
{% include 'advertisement/Adv.html' with inner_include='update' %}

templates/advertisement/AdvertisementAdd.html
{% extends 'base.html' %}

{% block title %}
Створення оголошення
{% endblock %}


{% block content %}
<div style="padding-top: 100px;"></div>

<p>Res: {{ user.is_moderator }}</p>
<form method="post" action="">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit"> Створити </button>
</form>
{% endblock %}

templates/advertisement/AdvertisementCreating.html
{% include 'advertisement/Adv.html' with inner_include='update' real_inner='create' %}

templates/advertisement/AdvertisementUpdate.html
{% extends 'base.html' %}

{% load i18n %}


{% block title %}
Оголошення - {{ advertisement.title }}
{% endblock %}


{% block content %}
<div style="padding-top: 100px;"></div>

<style>
body{
background-color:white;
box-sizing:border-box;
}
.main-content-block{
padding-top:100px;
}
.content{
position:relative;
width:100%;
height:110%;
background-color:#fafafa;
padding:0px 12% 0px 10%;
}
.container-images{
position:absolute;
width:42%;
height:35%;
margin-top:25px;
margin-left:5%;
border-radius: 15px;
border:5px solid 0;
background-color:#ebebeb;
}
.container-user{
position:absolute;
right:10%;
margin-top:25px;
margin-right:5%;
width:20%;
height:35%;
border-radius:15px;
border:5px solid 0;
background-color:#ebebeb;
}
.container-info-main{
position:absolute;
width:70%;
height:55%;
top:35%;
margin-top:50px;
margin-left:5%;
margin-right:5%;
}
.container-info{
width:100%;
height:90%;
top:55%;
border:5px solid 0;
background-color:#ebebeb;
}

</style>

<form method="post" action="">
    {% csrf_token %}
    <div class="main-content-block">
        <div class="content">
            <div class="container-images">
                {% include 'advertisement/includes/container-images.html'  %}
            </div>
            <div class="container-user">
                {% include 'advertisement/includes/container-user.html' %}
            </div>
            <div class="container-info-main">
                <div class="container-info">
                    {% include 'advertisement/includes/ContainerInfoForUpdate.html' with object=form %}
                </div>
                <div class="inner-button">
                    <button type="submit"> Зберегти</button>
                </div>
            </div>

        </div>
    </div>
</form>
{% endblock %}

templates/advertisement/DetailUpdateDeleteADV.html
{% extends 'base.html' %}

{% block content %}

<style>
body{
background-color:white;
box-sizing:border-box;
}
.main-content-block{
padding-top:100px;
}
.content{
position:relative;
width:100%;
height:110%;
background-color:#fafafa;
padding:0px 12% 0px 10%;
}
.container-images{
position:absolute;
width:42%;
height:35%;
margin-top:25px;
margin-left:5%;
border-radius: 15px;
border:5px solid 0;
background-color:#ebebeb;
}
.container-user{
position:absolute;
right:10%;
margin-top:25px;
margin-right:5%;
width:20%;
height:35%;
border-radius:15px;
border:5px solid 0;
background-color:#ebebeb;
}
.container-info-main{
position:absolute;
width:70%;
height:55%;
top:35%;
margin-top:50px;
margin-left:5%;
margin-right:5%;
}
.container-info{
width:100%;
height:90%;
top:55%;
border:5px solid 0;
background-color:#ebebeb;
}


</style>

<form method="post" action="">
    {% csrf_token %}
    <div class="main-content-block">
        <div class="content">
            <div class="container-images">
                {% include 'advertisement/includes/container-images.html' %}
            </div>
            <div class="container-user">
                {% include 'advertisement/includes/container-user.html' %}
            </div>
            <div class="container-info-main">
                <div class="container-info">
                    {% include 'advertisement/includes/container-info.html' %}
                </div>
                <button type="submit" class="btn btn-dark add"> Зберегти</button>

            </div>
        </div>
    </div>
</form>

{% endblock %}

templates/advertisement/archive.html
{% extends 'advertisement/AdvListMainTemplate.html' %}

{% block types %}
    <h1 style="text-align: center">Архів оголошень</h1>
{% endblock%}

{% block adv_buttons %}
    {% if user.is_moderator %}
    <a type="button"  href="" class="btn btn-warning update-button single">Опублікувати</a>
    {% endif %}
{% endblock %}