advertisement/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name='advertisement'

urlpatterns = [
    path('ads/', views.AdvList.as_view(), name='adv_list'),
    path('M-ads/', views.AdvListForModerator.as_view(), name='adv_list_for_moderators'),

    path('add/adv/', views.AdvAdd.as_view(), name='add_adv'),
    path('editing/<str:url_identifier>/', views.AdvUpdate.as_view(), name='update_adv'),

    path('adv/<str:url_identifier>/', views.AdvDetail.as_view(), name='adv_detail'),

    path('object/<str:type_>/', views.adv_by_type, name='adv_by_obj_type'),

    path('adv/<int:id>/archiving/', views.add_adv_to_archive, name='add_adv_to_archive'),

    path('archive/', views.Archive.as_view(), name='archive'),

    path('get-phone-ajax', views.get_adv_phone_ajax, name='get_adv_phone_ajax'),

    path('load-values-ajax/', views.load_values_ajax, name='load_values_ajax')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

# app_name = 'config'

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('', include('advertisement.urls')),
    path('', include('user.urls')),
    path('', include('filters.urls')),
    path('', include('auth_user.urls')),
    path('', include('site_messages.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.base_redirector, name='base_redirector_url'),
]

advertisement/models.py
import json
import os
from datetime import datetime
from translitua import translit

from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from .tools import store_serialized_data

OBJECT_TYPES = [
    ('flats', 'Квартири'),
    ('houses', 'Будинки'),
    ('plots', 'Земельні ділянки'),
    ('shops', 'Магазини'),
    ('warehouses', 'Складські приміщення'),
    ('offices', 'Офіси'),
    ('individual_buildings', 'Окремі будівлі')
]
ADS_TYPES = [
    ('Продаж', 'Продаж'),
    ('Оренда', 'Оренда')
]

CURRENCIES = [
    ('dollar', 'долар'),
    ('euro', 'євро'),
    ('grn', 'грн'),
]


class Region(models.Model):

    name = models.CharField(_('Область'), max_length=255, db_index=True)

    def __str__(self):
        return f'обл. {self.name}'

    class Meta:
        db_table = 'Region'


class City(models.Model):

    name = models.CharField(_("Місто"), max_length=255, db_index=True)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, related_name='cities', db_index=True)

    def __str__(self):
        return f'м. {self.name}'

    class Meta:
        db_table = 'City'


class District(models.Model):

    name = models.CharField(_('Район'), max_length=255, db_index=True)

    region = models.ForeignKey(Region, null=True, on_delete=models.SET_NULL, related_name='districts', db_index=True)
    city = models.ForeignKey(City, null=True, on_delete=models.SET_NULL, related_name='districts', db_index=True)

    is_city_district = models.BooleanField(default=False, blank=True, null=True)

    def __str__(self):
        return f'р. {self.name}'

    class Meta:
        db_table = 'District'


class Street(models.Model):

    name = models.CharField('Вулиця', max_length=255, db_index=True)

    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, related_name='streets', db_index=True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True, related_name='streets', db_index=True)

    def __str__(self):
        return f'вул. {self.name}'

    class Meta:
        db_table = 'Street'


class Advertisement(models.Model):

    date_pub = models.DateTimeField(_("Date of publication"), auto_now_add=True, null=True)

    region = models.ForeignKey(Region, on_delete=models.SET_NULL, related_name='ads', db_index=True, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, related_name='ads', db_index=True, null=True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, related_name='ads', db_index=True, null=True)
    street = models.ForeignKey(Street, on_delete=models.SET_NULL, related_name='ads', db_index=True, null=True)

    title = models.CharField(_("Назва оголошення"), max_length=250, db_index=True)
    title_slug = models.SlugField(max_length=250, blank=True, null=True, allow_unicode=True)
    new_title = models.CharField(max_length=250, db_index=True,blank=True, null=True)
    description = models.TextField(_("Опис"), blank=True, null=True)
    gen_desc = models.TextField(blank=True, null=True)

    currency = models.CharField(_("Валюта"), max_length=255,choices=CURRENCIES, blank=True, null=True)
    price = models.FloatField(_("Ціна"), max_length=255, blank=True, null=True)

    adv_type = models.CharField(_("Тип оголошення"),choices=ADS_TYPES,  max_length=255, blank=True, null=True)
    obj_type = models.CharField(choices=OBJECT_TYPES, blank=True, null=True, max_length=100)
    building = models.CharField(_("Будинок"), max_length=255, blank=True, null=True)

    photo_links = models.TextField(_("Посилання на фотографії"), blank=True, null=True)

    kitchen = models.CharField(_("Кухня"), max_length=255, blank=True, null=True)
    floor = models.CharField(_("Поверх"), max_length=255, blank=True, null=True)
    bathroom = models.CharField(_("Ванна"), max_length=255, blank=True, null=True)
    walls = models.CharField(_("Стіни"), blank=True, null=True, max_length=255)

    square = models.CharField(_("Площа"), max_length=255, blank=True, null=True)
    count_floors = models.CharField(_("Кількість поверхів"), max_length=255, blank=True, null=True)
    rooms = models.IntegerField(_("Кількість кімнат"), blank=True, null=True)

    heating = models.CharField(_("Опалення"), max_length=255, blank=True, null=True)
    remont = models.CharField(_("Ремонт"), max_length=255, blank=True, null=True, )
    planing = models.CharField(_("Планування"), max_length=255, blank=True, null=True, )

    seller_id = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(_("Номер телефону"), max_length=255, blank=True, null=True)
    original_url = models.CharField(max_length=255, blank=True, null=True)

    is_archival = models.BooleanField(null=False, default=False)
    date_archival = models.DateTimeField(default=None, null=True, blank=True)

    url_identifier = models.SlugField(max_length=255, null=True, unique=True, db_column='unique_adv_url_identifier',
                                       blank=True)

    def __getattribute__(self, item):
        if item == 'url_identifier':
            if not super().__getattribute__(item):
                self._set_url_identifier()
            return super().__getattribute__(item)
        else:
            return super().__getattribute__(item)

    def _set_url_identifier(self):
        self.url_identifier = slugify(translit(
            f'{"".join([i for i in self.region.name if i.isalnum()]) if self.region else "" }-'
            f'{"".join([i for i in self.street.name if i.isalnum()]) if self.street else "" }'
            f'-{Advertisement.objects.latest("id").id + 1}'
        ))


    def __str__(self):
        return f'<<{self.__class__.__name__} (id={self.id})>>'

    def save(self, *args, **kwargs):
        self.title_slug = slugify(self.title, allow_unicode=True)
        super(Advertisement, self).save(*args, **kwargs)

    def get_small_description(self, count=50):
        words = self.gen_desc.split(' ')
        if len(words) <= 50:
            return ' '.join(words)
        return ' '.join(words) + '...'

    def get_small_title(self):
        if self.new_title and len(self.new_title) > 35:
            return self.new_title[:32] + '...'
        return self.new_title

    def get_main_page_url(self):
        return reverse('advertisement:advertisement_list_for_customers')

    def get_absolute_url(self):
        return reverse('advertisement:adv_detail', kwargs={'url_identifier':self.url_identifier})

    def get_reviewing_images_url(self):
        return reverse('advertisement:reviewing_images_url', kwargs={'id': self.id})

    def get_test_phone(self):
        if not self.phone:
            return '+38-067-456-1233'
        return self.phone

    def get_test_date(self):
        if not self.date_pub:
            from django.utils import timezone
            return timezone.now()
        return self.date_pub

    def len_gen_title(self):
        if self.new_title:
            return len(self.new_title)

    def add_to_archive(self):
        self.is_archival = True
        self.date_archival = timezone.now()
        self.save()

    def get_title(self):
        if self.new_title and len(self.new_title) > 10:
            return self.new_title
        return self.title

    @classmethod
    def get_phone(cls, id):
        adv = cls.objects.get(id=id)
        if adv.phone:
            return adv.phone
        else:
            return '+38-096-234-1233'

    @classmethod
    def get_serialized_ads(cls, count=None, write=True):

        ads_properties = [
            adv.__dict__ for
            adv in cls.objects.order_by('?')[: count if count else cls.objects.count()]
        ]
        def _cleaning(data): del data['url_identifier']; del data['_state']; del data['id']

        [_cleaning(properties) for properties in ads_properties ]

        if write:
            store_serialized_data(ads_properties)
        return ads_properties

    @classmethod
    def create_from_file(cls, file=None, count='__all__'):
        ads_properties = json.load(open(file))

        count = len(ads_properties) if count == '__all__' else count
        ads = [
            cls.objects.create(**single_adv_property)
            for single_adv_property in ads_properties[:count]
        ]
        return ads

    @property
    def get_main_image(self):
        adv_images = self.images.all()
        return adv_images and adv_images[0].image.url

    get_images_count = property(lambda self: self.images.count())
    get_images = property(lambda self: [image.image.url for image in self.images.all()])

    get_full_address = property(lambda self: f'м. {self.city} \t вул. {self.street}')

    class Meta:
        db_table = 'Advertisement'
        ordering = ['-date_pub']

        verbose_name_plural = _('Advertisement')
        verbose_name = _('Advertisements')


def get_upload_path(instance, filename):
    filename = f"img_{instance.pk}_{filename.split('.')[-1]}"
    return os.path.join('ads_images', instance.adv.url_identifier, filename)


class AdvImage(models.Model):

    adv = models.ForeignKey(Advertisement, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=get_upload_path)
    upload_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'AdvImage'

advertisement/views.py
import logging

from django.views import generic
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views.generic.edit import FormView

from advertisement.models import Advertisement, Street, District, Region, City
from .forms import AdvUpdateForm, AdvAddForm
from . import services, decorators

from user import services as user_services
from site_messages.forms import MessageForm
from site_messages.services import MessageManager

logger = logging.getLogger(__name__)


class AdvList(services.AdvListMixin):
    template_name = 'advertisement/AdvList.html'

    def get(self, request):
        return super(AdvList, self).get(request)


class AdvListForModerator(services.AdvListMixin):
    template_name = 'advertisement/AdvListForModerator.html'


class AdvDetail(generic.DetailView):
    model = Advertisement

    slug_field = 'url_identifier'
    slug_url_kwarg = 'url_identifier'

    template_name = None  # I am using "template_setter" decorator for detecting template. Read why in doc
    context_object_name = 'advertisement'

    @decorators.template_setter
    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        user_services.UserAdv(adv=self.object, user=request.user).add_reviewed_adv_for_user()
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['random_adv'] = services.get_random_adv(current_adv_id=self.object.id)
        context['message_form'] = MessageForm()
        message_manager = MessageManager(self.request.GET.get('client_id'), self.object, self.request.user)
        context['messages'] = message_manager.get_messages()
        context['adv_clients'] = message_manager.clients_id if hasattr(message_manager, 'clients_id') else None
        return context

    @decorators.template_setter
    def post(self, request, url_identifier, *args, **kwargs):
        form = MessageForm(request.POST)

        if form.is_valid():
            manager = MessageManager(
                client_id=request.GET.get('client_id'),
                adv=Advertisement.objects.get( url_identifier= url_identifier), user=request.user
            )
            manager.send_messages(form.cleaned_data['text'])
            return HttpResponseRedirect(f'{request.get_full_path()}#messages-block')
        return render(request, self.template_name)


def adv_by_type(request, type_):
    ads_page_list = services.AdsPaginator(request.GET.get('page', 1), search_criteria=type_)
    context = ads_page_list.get_context()
    return render(request, 'advertisement/AdvList.html', context=context)


class AdvAdd(LoginRequiredMixin, CreateView):
    login_url = '/accounts/login/'

    template_name = 'advertisement/AdvertisementCreating.html'

    model = Advertisement
    form_class = AdvAddForm

    def post(self, request, *args, **kwargs):
        form = self.get_form(self.get_form_class())
        if form.is_valid():
            result = self.form_valid(form)
            services.store_adv_images(adv=self.object, images=request.FILES.getlist('images'))
            return result
        return render(request, self.template_name, {'form': form})


class AdvUpdate(PermissionRequiredMixin, UpdateView):

    permission_required = 'advertisement.change_advertisement'

    slug_field = 'url_identifier'
    slug_url_kwarg = 'url_identifier'

    template_name = 'advertisement/AdvUpdate.html'
    model = Advertisement
    form_class = AdvUpdateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['adv'] = self.object
        return context


def add_adv_to_archive(request, id):
    archiver = services.Archiver(id)
    return HttpResponseRedirect(archiver.get_end_point_for_redirect(request.GET.get('redirect_to')))


class Archive(services.AdvListMixin):
    template_name = 'advertisement/archive.html'
    order_by = '-date_archival'

    search_archival = True


def get_adv_phone_ajax(request):
    adv_id = request.POST.get('adv_id')

    phone = Advertisement.get_phone(adv_id)
    return JsonResponse({'adv_id': adv_id, 'button_id': request.POST.get('button_id'),
                         'is_authenticated': request.user.is_authenticated, 'phone': phone})


def load_values_ajax(request):
    field_changed = request.GET.get('field_changed')[1:]
    value_id = request.GET.get('value_id')

    if not value_id:
        return render(request, 'includes/dropdown_list_options.html')

    reg_id = request.GET.get('current_region')
    cit_id = request.GET.get('current_city')
    dist_id = request.GET.get('current_district')
    str_id = request.GET.get('current_street')

    current_region = Region.objects.get(id=reg_id) if reg_id else ''
    current_city = City.objects.get(id=cit_id) if cit_id else ''
    current_district = District.objects.get(id=dist_id) if dist_id else ''
    current_street = Street.objects.get(id=str_id) if str_id else ''

    if field_changed == 'id_region':
        regions = Region.objects.exclude(id=value_id)
        cities = City.objects.filter(region_id=value_id)
        districts = District.objects.filter(region_id=value_id, is_city_district=False)

    elif field_changed == 'id_city':
        streets = Street.objects.filter(city_id=value_id)
        districts = District.objects.filter(city_id=value_id)
        cities = City.objects.exclude(id=value_id)

        if len(districts) == 1:
            current_district = districts[0]
            districts = District.objects.filter(region_id=reg_id, is_city_district=False)
        else:
            current_district = None


    elif field_changed == 'id_district':
        current_city = current_district.city
        cities = City.objects.exclude(id=current_city.id)

        if current_district.is_city_district:
            districts = District.objects.filter(city=current_district.city, is_city_district=True)
        else:
            districts = District.objects.exclude(id=value_id, is_city_district=True)


    return render(request, 'includes/dropdown_list_options.html', locals())

templates/advertisement/includes/AdvList-Customers.html
{% include 'advertisement/AdvListMainTemplate.html' %}

templates/advertisement/includes/AdvertisementByObjectType.html
{% load static %}
{% load i18n %}
<style>

body{
}

a:link, a:visited {
    text-decoration: none;
}

.type-buttons{
    margin-top: 80px;
    width: 100%;
    display: flex;
}

.type{
    width: 25%;
    border-radius: 5px;
    background-color: #E7E7E7;
}

.type{
    margin:0;
    padding: 0;
}

.type:hover{
    background-color: #343a40;
}

.type-name:hover{
    color: aliceblue;
}

@media (max-width: 950px) {
    p.type-name{
        font-size: 17px;
    }
}

@media (max-width: 550px) {
    p.type-name{
        font-size: 14px;
    }
}

@media (max-width: 550px) {
    p.type-name{
        font-size: 12px;
    }
}

.type-name{
    margin: 0;
    font-size:20px;
    text-align: center;
}

.input-field{
    margin-top: 30px;
}

</style>




<section class="type-buttons">
    {% for type, type_name in types.items %}
        <a class="type" href="{% url 'advertisement:adv_by_obj_type' type %}" style="color:black;">
            <p class="type-name">{% translate type_name|title %}</p>
        </a>
    {% endfor %}
</section>

<section class="input-field">
    <form method="get" action="{% url 'advertisement:adv_list' %}">
        <div class="input-group mb-3">
            <input type="text" name="search" class="form-control" placeholder="Пошук за критеріями..." aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
            <button type="submit" class="input-group-text" id="inputGroup-sizing-default" >Пошук</button>
        </div>
    </form >
</section>

templates/advertisement/includes/add_images.html
<style>
.add-images-block{
    height: 500px;
    width: 100%;
}

#add-image-button{
    font-size: 65px;
    text-align: center;
    margin: 280px;
}

</style>

<div class="add-images-block">
    <a href="{% url 'advertisement:add_images' %}" id="add-image-button">Добавити фото</a>
</div>

templates/advertisement/includes/container-info.html
<div class="inner-adv-container-info">
    <div class="left-adv-info">
        <h1 class="main-adv-title">{{ advertisement.get_title }}</h1>
        <h2 class="main-adv-price"><strong>{{ advertisement.price }} {{ advertisement.currency }}</strong></h2>
        <br>
    </div>

    <div class="right-adv-info">
        {% if user.is_moderator %}
        <a type="button"  href="{% url 'advertisement:update_adv' advertisement.url_identifier %}" class="btn btn-warning update-button single">Редагувати</a>
        <a type="button" href="{% url 'advertisement:add_adv_to_archive' advertisement.id %}?end_point={{ request.get_full_path }}" class="btn btn-danger archive-button single" >Архівувати</a>
        {% endif %}

        <button type="button" id="get-phone" value="{{ advertisement.id }}" class="btn btn-light phone-button single">Взяти номер</button>
    </div>
</div>

<h5 class="main-adv-desc"><strong>ID оголошення: {{ advertisement.id }}</strong></h5>
<h5 class="main-adv-desc">{{advertisement.gen_desc}}</h5>


<div class="bottom-adv-info">
    <div class="inner-adv-bottom">

        <table class="table">

            {% if advertisement.region %}
                <tr class="table">
                    <th>Область:</th>
                    <td>{{ advertisement.region }}</td>
                </tr>
            {% endif %}

            {% if advertisement.city %}
                <tr class="table">
                    <th>Місто:</th>
                    <td>{{ advertisement.City }}</td>
                </tr>
            {% endif %}

            {% if advertisement.district %}
                <tr class="table">
                    <th>Район:</th>
                    <td>{{ advertisement.district }}</td>
                </tr>
            {% endif %}

            {% if advertisement.street %}
                <tr class="table">
                    <th>Вулиця:</th>
                    <td>{{ advertisement.street }}</td>
                </tr>
            {% endif %}

            {% if advertisement.price %}
                <tr class="table">
                    <th>Ціна:</th>
                    <td>{{ advertisement.price }}</td>
                </tr>
            {% endif %}

            {% if advertisement.currency %}
                <tr class="table">
                    <th>Валюта:</th>
                    <td>{{ advertisement.currency }}</td>
                </tr>
            {% endif %}

            {% if advertisement.adv_type %}
                <tr class="table">
                    <th>Тип оголошення:</th>
                    <td>{{ advertisement.adv_type }}</td>
                </tr>
            {% endif %}

            {% if advertisement.obj_type %}
                <tr class="table">
                    <th>Тип об'єкта:</th>
                    <td>{{ advertisement.obj_type }}</td>
                </tr>
            {% endif %}

            {% if advertisement.building %}
                <tr class="table">
                    <th>Будинок:</th>
                    <td>{{ advertisement.building }}</td>
                </tr>
            {% endif %}

            {% if advertisement.bathroom %}
                <tr class="table" >
                        <th >Ванна: </th>
                        <td >{{advertisement.bathroom}}</td>
                </tr>
            {% endif %}

            {% if advertisement.kitchen %}
                <tr class="table">
                        <th>Кухня:</th>
                        <td>{{ advertisement.kitchen }}</td>
                </tr>
            {% endif %}

            {% if advertisement.floor %}
                <tr class="table">
                    <th>Підлога:</th>
                    <td>{{ advertisement.floor }}</td>
                </tr>
            {% endif %}

            {% if advertisement.walls %}
                <tr class="table">
                    <th>Стіни:</th>
                    <td>{{ advertisement.walls }}</td>
                </tr>
            {% endif %}

            {% if advertisement.square %}
                <tr class="table">
                    <th>Площа:</th>
                    <td>{{ advertisement.square }}</td>
                </tr>
            {% endif %}

            {% if advertisement.count_floors %}
                <tr class="table">
                    <th>Кількість поверхів:</th>
                    <td>{{ advertisement.count_floors }}</td>
                </tr>
            {% endif %}

            {% if advertisement.rooms %}
                <tr class="table">
                    <th>Кімнати:</th>
                    <td>{{ advertisement.rooms }}</td>
                </tr>
            {% endif %}

            {% if advertisement.heating %}
                <tr class="table">
                    <th>Опалення:</th>
                    <td>{{ advertisement.heating }}</td>
                </tr>
            {% endif %}
            {% if advertisement.remont %}
                <tr class="table">
                    <th>Ремонт:</th>
                    <td>{{ advertisement.remont }}</td>
                </tr>
            {% endif %}

            {% if advertisement.planing %}
                <tr class="table">
                    <th>Планування:</th>
                    <td>{{ advertisement.planing }}</td>
                </tr>
            {% endif %}
        </table>

    </div>
</div>
<p class="adv-date">Дата Публікації: {{advertisement.get_test_date}}</p>
{% csrf_token %}

<script>
    $(document).ready(function () {
        var csrf = $("input[name=csrfmiddlewaretoken]").val()
        $("#get-phone").click(function (){
            $.ajax({
                url: "{% url 'advertisement:get_adv_phone_ajax' %}",
                type: 'post',
                data: {
                    csrfmiddlewaretoken: csrf,
                    adv_id: $(this).val(),
                    button_id: $(this).attr('id'),
                },
                success: function (response){
                    if (response.is_authenticated === false){
                        window.location.href = window.origin + `/accounts/login/?next=${window.location.href}`
                    } else {
                        phoneNumber = response.phone
                        changePhoneButton(response.button_id, phoneNumber)
                    }
                }
            })
        })
    })
</script>

templates/advertisement/includes/from-update-container-info.html
<form method="post" id="adv_form" enctype="multipart/form-data" data-ajax-url="{% url 'advertisement:load_values_ajax' %}">
    {% csrf_token %}

    {% if real_inner != 'create' %}
        <section class="generated-info" style="">
            <h1>Згенеровані данні</h1>
            <p class="main-adv-title">{{ form.new_title }}</p>
            <p class="main-adv-desc-update">{{form.gen_desc}}</p>
        </section>
    {% endif %}


    <section class="original-info">
        <h1>Оригінальні данні </h1>
        <p class="main-adv-title">{{ form.title }} </p>
        <p class="main-adv-desc-update">{{form.description}}</p>
    </section>

    {% if real_inner == 'create' %}
        <section id="add-images">
            {{ form.images }}
        </section>
    {% endif %}

    <section class="price-section">
        <h1 >Ціна</h1>
        <p class="price-field">{{ form.price }}</p>
        <p class="currency-field">{{ form.currency }}</p>
    </section>

    <section class="form-table-info">
        <table class="table">

            <tr class="table">
                <th>Область:</th>
                <td>{{ form.region }}</td>
            </tr>

            <tr class="table">
                <th>Місто:</th>
                <td>{{ form.city }}</td>
            </tr>

            <tr class="table">
                <th>Район:</th>
                <td>{{ form.district }}</td>
            </tr>

            <tr class="table">
                <th>Вулиця:</th>
                <td>{{ form.street }}</td>
            </tr>

            <tr class="table">
                <th>Ціна:</th>
                <td>{{ form.price }}</td>
            </tr>

            <tr class="table">
                <th>Валюта:</th>
                <td>{{ form.currency }}</td>
            </tr>

            <tr class="table">
                <th>Тип оголошення:</th>
                <td>{{ form.adv_type }}</td>
            </tr>

            <tr class="table">
                <th>Тип об'єкта:</th>
                <td>{{ form.obj_type }}</td>
            </tr>

            <tr class="table">
                <th>Будинок:</th>
                <td>{{ form.building }}</td>
            </tr>

            <tr class="table" >
                <th >Ванна: </th>
                <td >{{form.bathroom}}</td>
            </tr>

            <tr class="table">
                <th>Кухня:</th>
                <td>{{ form.kitchen }}</td>
            </tr>

            <tr class="table">
                <th>Підлога:</th>
                <td>{{ form.floor }}</td>
            </tr>

            <tr class="table">
                <th>Стіни:</th>
                <td>{{ form.walls }}</td>
            </tr>

            <tr class="table">
                <th>Площа:</th>
                <td>{{ form.square }}</td>
            </tr>

            <tr class="table">
                <th>Кількість поверхів:</th>
                <td>{{ form.count_floors }}</td>
            </tr>

            <tr class="table">
                <th>Кімнати:</th>
                <td>{{ form.rooms }}</td>
            </tr>

            <tr class="table">
                <th>Опалення:</th>
                <td>{{ form.heating }}</td>
            </tr>
            <tr class="table">
                <th>Ремонт:</th>
                <td>{{ form.remont }}</td>
            </tr>

            <tr class="table">
                <th>Планування:</th>
                <td>{{ form.planing }}</td>
            </tr>
        </table>

        {% if real_inner != 'create' %}
            <h1>Оригінальне посилання: <a href="{{ adv.original_url }}">{{ adv.original_url }}</a></h1>
        {% endif %}

    </section>
    <section class="update-form-buttons">
        {% if real_inner != 'create' %}
            <p class="adv-date list-buttons">Дата Публікації: {{advertisement.get_test_date}}</p>
        {% endif %}
        <input type="submit" class="btn btn-success save-button list-buttons" value="Зберегти">

        {% if real_inner != 'create' %}
            <a href="{{ advertisement.get_absolute_url }}" type="button" class="btn btn-light check-button list-buttons">Переглянути</a>
        {% endif %}
    </section>
</form>

<script>
    $("#id_region").change(function () {
        func_change("#id_region")
    });
    $("#id_city").change(function () {
        func_change("#id_city")
    });
    $("#id_district").change(function () {
        func_change("#id_district")
    });

    function get_el(field_name) {
        console.log('tessssssssssssssssssstttttttttttttttttttttttttttttttttt')
        return document.getElementById(field_name).value
    }

    function func_change(field_changed) {

        var url = $("#adv_form").attr("data-ajax-url");
        var value_id = document.getElementById(field_changed.slice(1,)).value

        $.ajax({
            url: url,
            data: {
                'value_id': value_id,
                'field_changed': field_changed,
                'current_region' : get_el('id_region'),
                'current_city': get_el('id_city'),
                'current_district': get_el('id_district'),
                'current_street': get_el('id_street'),
            },
            success: function (data) {
                section = document.createElement('section')
                section.innerHTML = data


                for (div_el of section.getElementsByTagName('div')) {
                    id = 'id_' + div_el.id.slice(0, div_el.id.length - 1)
                    console.log(id)
                    console.log(div_el.innerHTML)
                    document.getElementById(id).innerHTML = div_el.innerHTML
                }
            }
        });
    }
</script>