advertisement/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name='advertisement'

urlpatterns = [
    path('ads/', views.AdvList.as_view(), name='adv_list'),
    path('M-ads/', views.AdvListForModerator.as_view(), name='adv_list_for_moderators'),

    path('add/adv/', views.AdvAdd.as_view(), name='add_adv'),
    path('editing/<str:url_identifier>/', views.AdvUpdate.as_view(), name='update_adv'),

    path('adv/<str:url_identifier>/', views.AdvDetail.as_view(), name='adv_detail'),

    path('object/<str:type_>/', views.adv_by_type, name='adv_by_obj_type'),

    path('adv/<int:id>/archiving/', views.add_adv_to_archive, name='add_adv_to_archive'),

    path('archive/', views.Archive.as_view(), name='archive'),

    path('get-phone-ajax', views.get_adv_phone_ajax, name='get_adv_phone_ajax'),

    path('load-values-ajax/', views.load_values_ajax, name='load_values_ajax')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

# app_name = 'config'

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('', include('advertisement.urls')),
    path('', include('user.urls')),
    path('', include('filters.urls')),
    path('', include('auth_user.urls')),
    path('', include('site_messages.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.base_redirector, name='base_redirector_url'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('profile/', views.Profile.as_view(), name='profile'),
    path('likedAds/', views.UserLikedAds.as_view(), name='user_ads'),
    path('add-adv-ajax/', views.add_adv_ajax, name='add_adv_ajax'),
    path('hide-adv/<int:adv_id>', views.hide_adv, name='hide_adv'),
    path('hidden-ads/', views.HiddenAds.as_view(), name='hidden_ads'),
    path('viewed-ads/', views.ViewedAds.as_view(), name='viewed_ads'),
]

templates/base.html
{% load static %}

<html lang="ua">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">

    <title>{% block title %}Real-state-lviv{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    {% block js %} {% endblock %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block css %} {% endblock %}

    {% block extra %}{% endblock %}
</head>

<body>
{% include 'header.html' %}

<div id="container">
    <div id="main">
        {% block content %}{% endblock %}
    </div>
</div>

{% include 'footer.html' %}

</body>
</html>

templates/footer.html
<footer></footer>

templates/header.html
{% load i18n %}

<header>
    <div class="inner-header">
        <nav class="header-nav-left">
            {% if user.is_moderator %}
                <a href="{% url 'advertisement:adv_list_for_moderators' %}" style="margin-top: 20px;" type="button" class="" id="id_home_button">{% translate "Головна" %}</a>
                <a href="/my-messages/" style="margin-top: 20px;" type="button" class="" id="id_message_menu_button">Повідомлення</a>
            {% else  %}
                <a href="{% url 'advertisement:adv_list' %}" style="margin-top: 20px;" type="button" class="" id="id_home_button">{% translate "Головна" %}</a>
                <a href="/my-messages/" style="margin-top: 20px;" type="button" class="" id="id_message_menu_button">Повідомлення</a>
                <a href="{% url 'advertisement:add_adv' %}" style="margin-top: 20px;">Добавити оголошення</a>
            {% endif %}


            {% if user.is_customer %}
                <a href="{% url 'user:user_ads' %}" type="button" style="margin-top: 20px;">Корзина</a>
            {% elif user.is_moderator %}
                <a href="{% url 'advertisement:add_adv' %}" style="margin-top: 20px;">Добавити оголошення</a>
                <a href="{% url 'advertisement:archive' %}" style="margin-top: 20px;">Архів оголошень</a>
            {% endif %}
        </nav>
        <nav class="header-nav-right">

            {% if user.is_authenticated %}
            <a href="{% url 'user:profile' %}" style="margin-top: 20px;">Профіль</a>
            <a href="{% url 'account_logout' %}" style="margin-top: 20px;">Вийти</a>
            {% else %}
            <a href="{% url 'account_login' %}" style="margin-top: 20px;">Війти</a>
            <a href="{% url 'account_signup' %}" style="margin-top: 20px;">Зареєструватися</a>
            {% endif %}

            {% if user.is_superuser %}
            <a href="{% url 'admin:index' %}" style="margin-top: 20px;">Адмін панель</a>
            {% endif %}
        </nav>
    </div>
</header>