config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

# app_name = 'config'

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('', include('advertisement.urls')),
    path('', include('user.urls')),
    path('', include('filters.urls')),
    path('', include('auth_user.urls')),
    path('', include('site_messages.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.base_redirector, name='base_redirector_url'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('profile/', views.Profile.as_view(), name='profile'),
    path('likedAds/', views.UserLikedAds.as_view(), name='user_ads'),
    path('add-adv-ajax/', views.add_adv_ajax, name='add_adv_ajax'),
    path('hide-adv/<int:adv_id>', views.hide_adv, name='hide_adv'),
    path('hidden-ads/', views.HiddenAds.as_view(), name='hidden_ads'),
    path('viewed-ads/', views.ViewedAds.as_view(), name='viewed_ads'),
]

user/models.py
import logging

from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import AbstractUser, UserManager, Group
from django.db import models

from advertisement.models import Advertisement
from filters.models import Filter

logger = logging.getLogger(__name__)


class MainUserManager(UserManager):

    def create_moderator(self, username, password):
        user = self.create_user(username=username, password=password)
        group = Group.objects.get(name='moderators')

        user.groups.add(group)
        return user


class User(AbstractUser):
    """Custom User model"""

    objects = MainUserManager()

    _phone = PhoneNumberField(unique=True, null=True, db_column='phone')

    added_ads = models.ManyToManyField(Advertisement, default=None, blank=True, related_name='users_which_add')  #change related name
    hidden_ads = models.ManyToManyField(Advertisement, default=None, blank=True, related_name='users_which_hide')
    viewed_ads = models.ManyToManyField(Advertisement, default=None, blank=True, related_name='users_which_viewed')

    phone = property(lambda self: self._phone.as_e164)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def __str__(self):
        return self.username

    @property
    def is_customer(self):
        if 'moderators' not in [str(group) for group in self.groups.all()]:
            return True
        return False

    @property
    def is_moderator(self):
        if 'moderators' in [str(group) for group in self.groups.all()]:
            return True
        return False

    @property
    def status(self):
        if self.is_moderator:
            return 'Moderator'
        elif self.is_customer:
            return 'Customer'

    def hide_adv(self, adv):
        self.hidden_ads.add(adv)

    def add_reviewed_adv(self, adv):
        self.viewed_ads.add(adv)

    def all_reviewed_ads(self):
        return self.viewed_ads.all()

    class Meta:
        db_table = 'User'

user/views.py
import logging

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views import View
from django.http import JsonResponse

from . import services
from advertisement import services as adv_services

logger = logging.getLogger(__name__)


class UserLikedAds(View):

    def get(self, request):
        user_advertisement = request.user.added_ads.all()
        return render(request, 'user/UserAdvertisement.html', {'user_adv':user_advertisement})


class HiddenAds(adv_services.AdvListMixin):
    search_by_query = True
    template_name = 'user/hidden_ads.html'

    def set_query(self, request):
        self.query = request.user.hidden_ads.all()


class ViewedAds(adv_services.AdvListMixin):
    search_by_query = True
    template_name = 'user/viewed_ads.html'

    def set_query(self, request):
        self.query = request.user.all_reviewed_ads()


def add_adv_ajax(request):
    user_adv = services.UserAdv(adv_id=request.POST.get('adv_id'), user=request.user)
    user_adv.add_adv_for_user()
    return JsonResponse({'button_id':request.POST.get('button_id')}, status=200)


def hide_adv(request, adv_id):
    user_adv = services.UserAdv(adv_id=adv_id, user=request.user)
    user_adv.hide_adv_for_user()
    return HttpResponseRedirect(request.GET.get('end_point'))


class Profile(View):
    def get(self, request):
        return render(request, 'user/Profile.html')

templates/user/Profile.html
{% extends 'base.html' %}


{% block content %}

<style>
div{
    margin-top: 100px;
    width: 500px;
    margin-left: auto;
    margin-right: auto;
}
</style>

<div>
    <h1>User profile</h1>
    <p>username: {{ user.username }}</p>
    <p>status: {{user.status}}</p>
    <a href="{% url 'user:user_ads' %}" class="btn btn-light check-button single" style="float: none; width: fit-content;">Добавлені оголошення</a>
    <a href="{% url 'user:viewed_ads' %}" class="btn btn-light check-button single" style="float: none; width: fit-content">Переглянуті оголошення</a>
    <a href="{% url 'user:hidden_ads' %}" class="btn btn-light check-button single" style="float: none; width: fit-content">Приховані оголошення </a>
</div>


{% endblock %}

templates/user/UserAdvertisement.html
{% extends 'advertisement/AdvListMainTemplate.html' %}

{% block types %}
    <h1 style="text-align: center">Архів оголошень</h1>
{% endblock%}

{% block adv_buttons %}
{% endblock %}

templates/user/hidden_ads.html
{% extends 'advertisement/AdvListMainTemplate.html' %}

{% block types %}
    <h1 style="text-align: center">Приховані оголошення</h1>
{% endblock%}

{% block adv_buttons %}
    {% if user.is_moderator %}
    <a type="button"  href="" class="btn btn-warning update-button single">Видалити з прихованих</a>
    {% endif %}
{% endblock %}

templates/user/viewed_ads.html
{% extends 'advertisement/AdvListMainTemplate.html' %}

{% block types %}
    <h1 style="text-align: center">Переглянуті оголошення</h1>
{% endblock%}

{% block adv_buttons %}

{% endblock %}